version: "3.8"
services:
  client:
    stdin_open: true
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'
    volumes:
      - "/app/node_modules"
      - "./:/app"
