kind: Deployment
apiVersion: apps/v1
metadata:
  name: tfclient
  labels:
    app: tfclient
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tfclient
  template:
    metadata:
      labels:
        app: tfclient
    spec:
      containers:
        - name: tfclient
          image: qweliant/tfclient
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
                limits:
                    memory: '512Mi'
                    cpu: '200m'
          livenessProbe:
                httpGet:
                    path: /index.html
                    port: 80
                initialDelaySeconds: 15
                timeoutSeconds: 2
                periodSeconds: 5
                failureThreshold: 1
          readinessProbe:
              httpGet:
                  path: /index.html
                  port: 80
              initialDelaySeconds: 15
              periodSeconds: 5
              failureThreshold: 1
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: tfclient
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: tfclient